development:
  adapter: postgresql
  encoding: unicode
  database: cosmos_dev
  pool: 5
  username: martinezcoder
  password: baruco2012
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: cosmos_test
  pool: 5
  username: martinezcoder
  password: baruco2012
  timeout: 5000

